CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar(25) NOT NULL,
  "age" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(200) UNIQUE NOT NULL,
  "description" text NOT NULL,
  "level" int NOT NULL,
  "teacher" int NOT NULL
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(200) NOT NULL,
  "url" varchar UNIQUE NOT NULL,
  "course" int NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(40) UNIQUE NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) UNIQUE NOT NULL
);

CREATE TABLE "levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) UNIQUE NOT NULL
);

CREATE TABLE "roles_users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" int NOT NULL,
  "user" int NOT NULL
);

CREATE TABLE "users_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course" int NOT NULL,
  "user" int NOT NULL
);

CREATE TABLE "categories_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course" int NOT NULL,
  "category" int NOT NULL
);

ALTER TABLE "courses" ADD FOREIGN KEY ("level") REFERENCES "levels" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher") REFERENCES "users" ("id");

ALTER TABLE "roles_users" ADD FOREIGN KEY ("role") REFERENCES "roles" ("id");

ALTER TABLE "roles_users" ADD FOREIGN KEY ("user") REFERENCES "users" ("id");

ALTER TABLE "course_video" ADD FOREIGN KEY ("course") REFERENCES "courses" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("user") REFERENCES "users" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("course") REFERENCES "courses" ("id");

ALTER TABLE "categories_courses" ADD FOREIGN KEY ("course") REFERENCES "courses" ("id");

ALTER TABLE "categories_courses" ADD FOREIGN KEY ("category") REFERENCES "categories" ("id");

INSERT INTO "roles" ("name") VALUES ('admin'), ('teacher'), ('student');

INSERT INTO "levels" ("name") VALUES ('begginer'), ('intemediate'), ('advanced');

INSERT INTO "categories" ("name") VALUES ('tech'), ('science'), ('art');

INSERT INTO "users" ("name", "email", "password", "age") VALUES 
('Samael', 'samael@email.com', 'samael1234', 26),
('María', 'maria@email.com', 'maria1234', 35),
('Carolina', 'carolina@gmail.com', 'caro1234', 25),
('Adrian', 'adrian@email.com', 'adrian1234', 18);

INSERT INTO "roles_users" ("user", "role") VALUES (1, 1), (1, 2), (2, 2), (3, 3), (4, 3);

INSERT INTO "users_courses" ("course", "user") VALUES (1, 2), (1, 3), (1, 4), (2, 1), (2, 3);

INSERT INTO "courses" ("title", "description", "level", "teacher") VALUES 
('react web development', 'curso de diseño front end en react para principiantes', 1, 2),
('data analysis with python', 'curso sobre recolección, interpretación, manejo y aplicación de datos con python', 2, 1),
('landscape photography techniques', 'curso avanzado sobre fotografía paisajista, para sacarle el máximo provecho a tus fotografías', 3, 2);

INSERT INTO "course_video" ("title", "url", "course") VALUES 
('setting up manual configurations on your dslr camera', 'https://mivideo.com/asd1234vid001', 3),
('fitering and ordening raw data', 'https://mivideo.com/asd1234vid002', 2);

INSERT INTO "categories_courses" ("course", "category") VALUES (1, 1), (2, 1), (2, 2), (3, 3);
